# Generated by Django 3.0.2 on 2020-01-30 05:08

import clubcell.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='eventstodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAN', models.CharField(max_length=100)),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_UAP', models.CharField(max_length=13, unique=True)),
                ('breif_about', models.CharField(max_length=90)),
                ('detail_about', models.CharField(max_length=2000)),
                ('tags', models.CharField(max_length=100)),
                ('eventname', models.CharField(max_length=100)),
                ('eventtype', models.CharField(max_length=20)),
                ('season', models.IntegerField()),
                ('heldon', models.DateTimeField(max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('fee', models.IntegerField()),
                ('certificate', models.BooleanField(default=False)),
                ('dl', models.BooleanField(default=False)),
                ('show_public', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='eventdone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAN', models.CharField(max_length=100)),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_UAP', models.CharField(max_length=13, unique=True)),
                ('eventname', models.CharField(max_length=100)),
                ('session', models.IntegerField()),
                ('members', models.IntegerField()),
                ('attended', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('reviews', models.IntegerField()),
                ('breif_about', models.CharField(max_length=90)),
                ('eventtype', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('heldon', models.DateTimeField(max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('fee', models.IntegerField()),
                ('certificate', models.BooleanField(default=False)),
                ('dl', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAN', models.CharField(max_length=100, unique=True)),
                ('profile_pic', models.ImageField(upload_to=clubcell.models.get_upload_path)),
                ('gender', models.CharField(default='male', max_length=6)),
                ('having_club', models.BooleanField(default=False)),
                ('phone_no', models.CharField(default='+91', max_length=13)),
                ('branch', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('reg_no', models.CharField(max_length=10)),
                ('intrests', models.CharField(max_length=5000)),
                ('follower', models.CharField(max_length=5000)),
                ('following', models.CharField(max_length=5000)),
                ('unseen_messages', models.IntegerField(default=0)),
                ('unseen_alerts', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='clubcell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAN', models.CharField(max_length=100, unique=True)),
                ('clubname', models.CharField(max_length=30)),
                ('off_email', models.CharField(default='', max_length=100)),
                ('tel', models.IntegerField(default=91)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('reputation', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('about', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
