# Generated by Django 3.0.2 on 2020-01-31 06:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubcell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('another', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=120)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime(2020, 1, 31, 6, 21, 38, 232339, tzinfo=utc))),
                ('alerts_in', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('visible', models.BooleanField(default=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 1, 31, 6, 21, 38, 246516, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='event_participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('payment_done', models.BooleanField(default=False)),
                ('payment_status', models.CharField(max_length=120)),
                ('personal_info_access', models.CharField(default='all,', max_length=1000)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 1, 31, 6, 21, 38, 244333, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAN', models.CharField(max_length=100)),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_UAP', models.CharField(max_length=13, unique=True)),
                ('eventname', models.CharField(max_length=100)),
                ('session', models.IntegerField()),
                ('members', models.IntegerField()),
                ('attended', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('reviews', models.IntegerField()),
                ('breif_about', models.CharField(max_length=90)),
                ('eventtype', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('heldon', models.DateTimeField(max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('fee', models.IntegerField()),
                ('certificate', models.BooleanField(default=False)),
                ('dl', models.BooleanField(default=False)),
                ('event_complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ManyToManyField(related_name='_following_follower_+', to='clubcell.following')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=1)),
                ('related_tags', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 1, 31, 6, 21, 38, 245984, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(choices=[('H', 'Head'), ('L', 'Leader'), ('CL', 'Co-Leader'), ('CN', 'Coordinator')], default='CN', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('another', models.CharField(max_length=100)),
                ('receive_or_sent', models.CharField(default='receive', max_length=10)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime(2020, 1, 31, 6, 21, 38, 231923, tzinfo=utc))),
                ('message_type', models.CharField(default='text', max_length=10)),
                ('message_in', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('T', 'Text'), ('V', 'Video'), ('I', 'Image')], default='I', max_length=1)),
                ('image', models.ImageField(blank=True, upload_to='posts/images')),
                ('video', models.FileField(blank=True, upload_to='posts/videos')),
                ('text', models.CharField(blank=True, max_length=200)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 1, 31, 6, 21, 38, 245348, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('visible', models.BooleanField(default=False)),
                ('vulgar', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 1, 31, 6, 21, 38, 244826, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 1, 31, 6, 21, 38, 242658, tzinfo=utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='eventstodo',
            name='user',
        ),
        migrations.AlterField(
            model_name='clubcell',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='eventdone',
        ),
        migrations.DeleteModel(
            name='eventstodo',
        ),
        migrations.AddField(
            model_name='team',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubcell.clubcell'),
        ),
        migrations.AddField(
            model_name='review',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubcell.clubcell'),
        ),
        migrations.AddField(
            model_name='review',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubcell.events'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubcell.clubcell'),
        ),
        migrations.AddField(
            model_name='posts',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubcell.events'),
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='members',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubcell.clubcell'),
        ),
        migrations.AddField(
            model_name='members',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubcell.team'),
        ),
        migrations.AddField(
            model_name='members',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='post_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubcell.posts'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event_participants',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubcell.clubcell'),
        ),
        migrations.AddField(
            model_name='event_participants',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubcell.events'),
        ),
        migrations.AddField(
            model_name='event_participants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='post_commented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubcell.posts'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
