# Generated by Django 3.0.2 on 2020-01-31 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0006_auto_20200131_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 9, 13, 49, 243009, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 9, 13, 49, 257455, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event_participants',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 9, 13, 49, 255221, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 9, 13, 49, 256974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 9, 13, 49, 242596, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 9, 13, 49, 256347, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 9, 13, 49, 255790, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubcell.clubcell'),
        ),
        migrations.AlterField(
            model_name='team',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 9, 13, 49, 253619, tzinfo=utc)),
        ),
    ]
