# Generated by Django 3.0.2 on 2020-01-31 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0011_auto_20200131_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='details',
            name='following',
        ),
        migrations.RemoveField(
            model_name='details',
            name='intrests',
        ),
        migrations.RemoveField(
            model_name='details',
            name='unseen_alerts',
        ),
        migrations.RemoveField(
            model_name='details',
            name='unseen_messages',
        ),
    ]
