# Generated by Django 3.0.2 on 2020-01-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0012_auto_20200131_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubcell',
            name='tel',
            field=models.CharField(default=91, max_length=12),
        ),
    ]
