# Generated by Django 3.0.2 on 2020-02-03 02:08

import clubcell.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubcell', '0013_auto_20200131_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='PAN',
            field=models.CharField(default=clubcell.models.pan_generate, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='another',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='another', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
