# Generated by Django 3.0.2 on 2020-02-03 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubcell', '0014_auto_20200203_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='another',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='another',
        ),
        migrations.AddField(
            model_name='alerts',
            name='second_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alert_second_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messages',
            name='second_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
