# Generated by Django 3.0.2 on 2020-02-03 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubcell', '0018_auto_20200203_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubcell',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubcell', to=settings.AUTH_USER_MODEL),
        ),
    ]
