# Generated by Django 3.0.2 on 2020-02-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0020_auto_20200203_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_complete',
            field=models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('C', 'Canceled')], default='P', max_length=1),
        ),
    ]
