# Generated by Django 3.0.2 on 2020-02-03 15:36

import clubcell.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0021_auto_20200203_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_id',
            field=models.CharField(default=clubcell.models.pan_generate, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventtype',
            field=models.CharField(choices=[('WS', 'Workshop'), ('CP', 'Competition'), ('CC', 'Concert')], default='WS', max_length=2),
        ),
    ]
