# Generated by Django 3.0.2 on 2020-02-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0022_auto_20200203_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='receive_or_sent',
            field=models.CharField(choices=[('S', 'Sent'), ('R', 'Received')], default='R', max_length=1),
        ),
    ]
