# Generated by Django 3.0.2 on 2020-02-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0023_auto_20200204_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('T', 'Text'), ('I', 'Image'), ('A', 'Audio'), ('V', 'Video')], default='T', max_length=1),
        ),
    ]
