# Generated by Django 3.0.2 on 2020-02-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0024_auto_20200204_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='privacy',
            field=models.CharField(choices=[('OM', 'Only Me'), ('MB', 'Members of this club'), ('PB', 'Public')], default='PB', max_length=2),
        ),
        migrations.AddField(
            model_name='events',
            name='registration',
            field=models.BooleanField(default=True),
        ),
    ]
