# Generated by Django 3.0.2 on 2020-02-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0026_auto_20200204_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_detail',
            field=models.CharField(default='<font size="20px" color="RED">detail of this event is not given</font>', max_length=2000),
        ),
    ]
