# Generated by Django 3.0.2 on 2020-02-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0028_auto_20200204_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='receive_or_sent',
        ),
    ]
