# Generated by Django 3.0.2 on 2020-02-08 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubcell', '0029_remove_messages_receive_or_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='typing_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typing', models.BooleanField(default=False)),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_message_2', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
