# Generated by Django 3.0.2 on 2020-02-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0030_typing_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='members',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='season',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='events',
            name='session',
            field=models.IntegerField(default=1),
        ),
    ]
