# Generated by Django 3.0.2 on 2020-02-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0031_auto_20200209_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
