# Generated by Django 3.0.2 on 2020-02-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0034_auto_20200209_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_participants',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to='clubcell.events'),
        ),
        migrations.AlterField(
            model_name='event_participants',
            name='payment_status',
            field=models.CharField(default='null', max_length=120),
        ),
    ]
