# Generated by Django 3.0.2 on 2020-02-09 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubcell', '0035_auto_20200209_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_participants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
