# Generated by Django 3.0.2 on 2020-02-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0037_auto_20200210_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_participants',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event_participants',
            name='highlight_reason',
            field=models.CharField(default='null', max_length=120),
        ),
    ]
