# Generated by Django 3.0.2 on 2020-02-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0039_typing_message_last_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='profile_pic',
            field=models.ImageField(default='profile.jpg', upload_to='profile_images'),
        ),
    ]
