# Generated by Django 3.0.2 on 2020-02-18 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubcell', '0040_auto_20200217_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_wishlist', to='clubcell.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
