# Generated by Django 3.0.2 on 2020-03-10 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubcell', '0041_event_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='profile_pic',
            field=versatileimagefield.fields.VersatileImageField(default='profile.jpg', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='members',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clubcell.team'),
        ),
        migrations.AlterField(
            model_name='members',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='clubcell.clubcell'),
        ),
    ]
