# Generated by Django 3.0.2 on 2020-03-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0042_auto_20200310_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clubcell.events'),
        ),
    ]
