# Generated by Django 3.0.2 on 2020-03-10 14:34

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0044_auto_20200310_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='posts/images'),
        ),
    ]
