# Generated by Django 3.0.2 on 2020-03-14 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubcell', '0046_auto_20200310_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='parent_event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clubcell.group_event'),
        ),
        migrations.CreateModel(
            name='event_query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=350)),
                ('visible', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('replied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_query', to='clubcell.event_query')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_query', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
