# Generated by Django 3.0.2 on 2020-03-14 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0047_auto_20200314_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_query',
            name='replied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_query', to='clubcell.event_query'),
        ),
    ]
