# Generated by Django 3.0.2 on 2020-03-15 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0048_auto_20200314_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_query',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event_query', to='clubcell.events'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event_query',
            name='replied',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_query', to='clubcell.event_query'),
        ),
    ]
