# Generated by Django 3.0.2 on 2020-03-23 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0050_event_query_replied_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubcell.events'),
        ),
    ]
