# Generated by Django 3.0.2 on 2020-03-26 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0051_messages_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='parent_event',
        ),
        migrations.AddField(
            model_name='events',
            name='group_event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='clubcell.group_event'),
        ),
        migrations.AddField(
            model_name='group_event',
            name='parent_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_event', to='clubcell.group_event'),
        ),
    ]
