# Generated by Django 3.0.2 on 2020-03-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0052_auto_20200326_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_event',
            name='thumbnail',
            field=models.CharField(default='https://i.redd.it/b3esnz5ra34y.jpg', max_length=500),
        ),
    ]
