# Generated by Django 3.0.2 on 2020-03-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0053_group_event_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_event',
            name='group_name',
            field=models.CharField(max_length=30),
        ),
    ]
