# Generated by Django 3.0.2 on 2020-03-28 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubcell', '0055_custom_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_input_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubcell.custom_input')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
