# Generated by Django 3.0.2 on 2020-03-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0056_custom_input_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='custom_inputs',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='clubcell.custom_input'),
        ),
    ]
