# Generated by Django 3.0.2 on 2020-03-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0057_events_custom_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_input',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
