# Generated by Django 3.0.2 on 2020-03-29 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubcell', '0058_custom_input_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='custom_inputs',
            field=models.ManyToManyField(blank=True, default=None, to='clubcell.custom_input'),
        ),
        migrations.AlterField(
            model_name='following',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
