# Generated by Django 3.0.2 on 2020-03-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0061_auto_20200329_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='related_images',
            name='type',
            field=models.CharField(default='collapse', max_length=50),
        ),
    ]
