# Generated by Django 3.0.2 on 2020-04-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0062_related_images_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
