# Generated by Django 3.0.2 on 2020-04-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0063_posts_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
