# Generated by Django 3.0.2 on 2020-04-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0064_auto_20200401_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
