# Generated by Django 3.0.2 on 2020-04-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0066_auto_20200402_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_input',
            name='input_type',
            field=models.CharField(choices=[('T', 'Text'), ('I', 'Integer'), ('C', 'Choice'), ('EMAIL', 'email'), ('RADIO', 'Radio'), ('MC', 'Multiple Choice')], default='T', max_length=20),
        ),
    ]
