# Generated by Django 3.0.2 on 2020-04-03 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubcell', '0067_auto_20200402_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='cash_accept',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='events',
            name='cash_receivers',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='paytm_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='upi_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custom_input',
            name='input_type',
            field=models.CharField(choices=[('T', 'Text'), ('I', 'Number'), ('C', 'Choice'), ('EMAIL', 'Email'), ('RADIO', 'Radio'), ('MC', 'Multiple Choice')], default='T', max_length=20),
        ),
    ]
