# Generated by Django 3.0.2 on 2020-04-03 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0068_auto_20200403_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_input',
            name='club',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubcell.clubcell'),
        ),
        migrations.AddField(
            model_name='custom_input',
            name='event',
            field=models.ManyToManyField(blank=True, default=None, to='clubcell.events'),
        ),
    ]
