# Generated by Django 3.0.2 on 2020-04-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0069_auto_20200403_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_input',
            name='input_type',
            field=models.CharField(choices=[('T', 'Text'), ('I', 'Number'), ('C', 'Choice'), ('EMAIL', 'Email'), ('RADIO', 'Radio'), ('TEL', 'Tel'), ('MC', 'Multiple Choice')], default='T', max_length=20),
        ),
    ]
