# Generated by Django 3.0.2 on 2020-04-03 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubcell', '0070_auto_20200403_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_participants',
            name='cash_accepter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event_participants',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='custom_input_value',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_input_value', to=settings.AUTH_USER_MODEL),
        ),
    ]
