# Generated by Django 3.0.2 on 2020-04-03 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubcell', '0071_auto_20200403_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_participants',
            old_name='cash_accepter',
            new_name='cash_acceptor',
        ),
        migrations.AlterField(
            model_name='alerts',
            name='second_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_second_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
