# Generated by Django 3.0.2 on 2020-04-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0072_auto_20200403_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='certificate_detail',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='events',
            name='dl_detail',
            field=models.CharField(default='', max_length=250),
        ),
    ]
