# Generated by Django 3.0.2 on 2020-04-10 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0073_auto_20200406_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_input',
            name='event',
        ),
        migrations.AddField(
            model_name='custom_input',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubcell.events'),
        ),
    ]
