# Generated by Django 3.0.2 on 2021-01-24 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubcell', '0074_auto_20200410_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubcell.clubcell'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubcell.events'),
        ),
    ]
